import { prisma } from '@/lib/db'
import bcrypt from 'bcryptjs'

async function main() {
  console.log('Seeding database...')

  // ── Admin User ──────────────────────────────────────────────────────────
  const hashedPassword = await bcrypt.hash('Admin123!', 12)

  const admin = await prisma.user.upsert({
    where: { email: 'admin@yuanbridge.com' },
    update: {},
    create: {
      name: 'Admin',
      nameAr: 'مدير',
      email: 'admin@yuanbridge.com',
      password: hashedPassword,
      role: 'ADMIN',
      language: 'en',
      theme: 'dark',
      emailNotifications: true,
      pushNotifications: true,
    },
  })
  console.log(`  ✓ Admin user created (${admin.email})`)

  // ── Sample Users ────────────────────────────────────────────────────────
  const userPassword = await bcrypt.hash('User1234!', 12)

  const users = await Promise.all([
    prisma.user.upsert({
      where: { email: 'ahmed@example.com' },
      update: {},
      create: {
        name: 'Ahmed Hassan',
        nameAr: 'أحمد حسن',
        email: 'ahmed@example.com',
        password: userPassword,
        role: 'USER',
        language: 'ar',
        theme: 'dark',
      },
    }),
    prisma.user.upsert({
      where: { email: 'sarah@example.com' },
      update: {},
      create: {
        name: 'Sarah Johnson',
        nameAr: 'سارة جونسون',
        email: 'sarah@example.com',
        password: userPassword,
        role: 'USER',
        language: 'en',
        theme: 'light',
      },
    }),
    prisma.user.upsert({
      where: { email: 'omar@example.com' },
      update: {},
      create: {
        name: 'Omar Khaled',
        nameAr: 'عمر خالد',
        email: 'omar@example.com',
        password: userPassword,
        role: 'USER',
        language: 'ar',
        theme: 'dark',
      },
    }),
    prisma.user.upsert({
      where: { email: 'emma@example.com' },
      update: {},
      create: {
        name: 'Emma Wilson',
        nameAr: 'إيما ويلسون',
        email: 'emma@example.com',
        password: userPassword,
        role: 'USER',
        language: 'en',
        theme: 'light',
      },
    }),
  ])
  console.log(`  ✓ ${users.length} sample users created`)

  // ── Subscriptions ───────────────────────────────────────────────────────
  const now = new Date()
  const thirtyDays = 30 * 24 * 60 * 60 * 1000
  const ninetyDays = 90 * 24 * 60 * 60 * 1000

  const subscriptions = [
    { userId: users[0].id, plan: 'PREMIUM' as const, status: 'ACTIVE' as const, start: new Date(now.getTime() - ninetyDays), end: new Date(now.getTime() + ninetyDays) },
    { userId: users[1].id, plan: 'PREMIUM' as const, status: 'ACTIVE' as const, start: new Date(now.getTime() - thirtyDays), end: new Date(now.getTime() + thirtyDays) },
    { userId: users[2].id, plan: 'FREE' as const, status: 'TRIALING' as const, start: now, end: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000) },
    { userId: users[3].id, plan: 'PREMIUM' as const, status: 'ACTIVE' as const, start: new Date(now.getTime() - sixtyDays(60)), end: new Date(now.getTime() + sixtyDays(30)) },
  ]

  for (const sub of subscriptions) {
    await prisma.subscription.upsert({
      where: { userId: sub.userId },
      update: {},
      create: {
        userId: sub.userId,
        plan: sub.plan,
        status: sub.status,
        startedAt: sub.start,
        endsAt: sub.end,
      },
    })
  }
  console.log(`  ✓ ${subscriptions.length} subscriptions created`)

  // ── Strategies ──────────────────────────────────────────────────────────
  interface StrategyData {
    title: string
    titleAr: string
    currencyPair: string
    direction: 'BUY' | 'SELL'
    entryPrice: number
    stopLoss: number
    takeProfit1: number
    takeProfit2: number
    risk: 'LOW' | 'MEDIUM' | 'HIGH'
    confidence: number
    summary: string
    summaryAr: string
    trend: 'BULLISH' | 'BEARISH' | 'NEUTRAL'
    technicalAnalysis: string
    technicalAnalysisAr: string
    fundamentalAnalysis: string
    fundamentalAnalysisAr: string
    isPremium: boolean
    isPublished: boolean
    isApproved: boolean
    rsi: number
    macdValue: number
    macdSignal: number
    macdHistogram: number
    emaFast: number
    emaSlow: number
    smaPeriod: number
    smaValue: number
    atr: number
    bbUpper: number
    bbMiddle: number
    bbLower: number
    support1: number
    support2: number
    support3: number
    resistance1: number
    resistance2: number
    resistance3: number
    tradesAnalyzed: number
    aiModel: string
    aiProvider: 'OPENAI' | 'CLAUDE' | 'GEMINI' | 'DEEPSEEK'
    notes: string
    notesAr: string
  }

  const strategiesData: StrategyData[] = [
    {
      title: 'EUR/USD Bullish Breakout',
      titleAr: 'انفراج صاعد لليورو مقابل الدولار',
      currencyPair: 'EUR/USD',
      direction: 'BUY',
      entryPrice: 1.0875,
      stopLoss: 1.0790,
      takeProfit1: 1.0950,
      takeProfit2: 1.1020,
      risk: 'MEDIUM',
      confidence: 82,
      summary: 'Bullish breakout above resistance with strong momentum. RSI shows room for further upside.',
      summaryAr: 'انفراج صاعد فوق المقاومة مع زخم قوي. مؤشر القوة النسبية يظهر مساحة لمزيد من الصعود.',
      trend: 'BULLISH',
      technicalAnalysis: 'Price broke above the descending trendline on the 4H chart. Bollinger Bands are widening suggesting increased volatility. MACD crossed above signal line with bullish histogram. RSI at 62, not yet overbought. Key support at 1.0820.',
      technicalAnalysisAr: 'اخترق السعر فوق خط الاتجاه الهابط على الرسم البياني لأربع ساعات. نطاقات بولينجر تتسع مما يشير إلى زيادة التقلب. تقاطع مؤشر MACD فوق خط الإشارة مع رسم بياني صاعد. مؤشر القوة النسبية عند 62، لم يصل بعد إلى منطقة التشبع الشرائي. الدعم الرئيسي عند 1.0820.',
      fundamentalAnalysis: 'ECB hawkish stance supports EUR. US economic data mixed with weaker retail sales. Interest rate differential narrowing in favor of EUR.',
      fundamentalAnalysisAr: 'موقف البنك المركزي الأوروبي المتشدد يدعم اليورو. بيانات اقتصادية أمريكية مختلطة مع مبيعات تجزئة أضعف. فجوة أسعار الفائدة تضيق لصالح اليورو.',
      isPremium: false,
      isPublished: true,
      isApproved: true,
      rsi: 62,
      macdValue: 0.0012,
      macdSignal: 0.0008,
      macdHistogram: 0.0004,
      emaFast: 1.0855,
      emaSlow: 1.0820,
      smaPeriod: 50,
      smaValue: 1.0830,
      atr: 0.0045,
      bbUpper: 1.0920,
      bbMiddle: 1.0850,
      bbLower: 1.0780,
      support1: 1.0820,
      support2: 1.0780,
      support3: 1.0720,
      resistance1: 1.0900,
      resistance2: 1.0950,
      resistance3: 1.1020,
      tradesAnalyzed: 1247,
      aiModel: 'gpt-4-turbo',
      aiProvider: 'OPENAI',
      notes: 'Watch NFP release this Friday. Reduce position size if volatility spikes.',
      notesAr: 'ترقب إصدار بيانات الوظائف غير الزراعية يوم الجمعة. قلل حجم المركز إذا ارتفعت التقلبات.',
    },
    {
      title: 'GBP/USD Bearish Reversal',
      titleAr: 'انعكاس هابط للجنيه مقابل الدولار',
      currencyPair: 'GBP/USD',
      direction: 'SELL',
      entryPrice: 1.2650,
      stopLoss: 1.2720,
      takeProfit1: 1.2580,
      takeProfit2: 1.2510,
      risk: 'HIGH',
      confidence: 76,
      summary: 'Bearish engulfing pattern on daily close. UK economic outlook weakening.',
      summaryAr: 'نمط ابتلاع هابط على الإغلاق اليومي. التوقعات الاقتصادية للمملكة المتحدة تضعف.',
      trend: 'BEARISH',
      technicalAnalysis: 'Bearish engulfing candle formed at resistance. RSI diverging bearishly. MACD about to cross below signal. Volume increasing on sell-off. Next support at 1.2550.',
      technicalAnalysisAr: 'تشكلت شمعة ابتلاع هابطة عند المقاومة. مؤشر القوة النسبية يظهر تباعدًا هابطًا. مؤشر MACD على وشك التقاطع أسفل الإشارة. حجم التداول يزيد مع البيع. الدعم التالي عند 1.2550.',
      fundamentalAnalysis: 'BoE expected to cut rates sooner than anticipated. UK GDP growth slowing. Services PMI contracting.',
      fundamentalAnalysisAr: 'من المتوقع أن يخفض بنك إنجلترا أسعار الفائدة في وقت أقرب من المتوقع. نمو الناتج المحلي الإجمالي للمملكة المتحدة يتباطأ. مؤشر مديري المشتريات الخدمي في انكماش.',
      isPremium: true,
      isPublished: true,
      isApproved: true,
      rsi: 68,
      macdValue: -0.0008,
      macdSignal: -0.0003,
      macdHistogram: -0.0005,
      emaFast: 1.2670,
      emaSlow: 1.2695,
      smaPeriod: 50,
      smaValue: 1.2660,
      atr: 0.0050,
      bbUpper: 1.2750,
      bbMiddle: 1.2640,
      bbLower: 1.2530,
      support1: 1.2580,
      support2: 1.2550,
      support3: 1.2480,
      resistance1: 1.2700,
      resistance2: 1.2750,
      resistance3: 1.2800,
      tradesAnalyzed: 892,
      aiModel: 'claude-3-opus',
      aiProvider: 'CLAUDE',
      notes: 'Risk of BOE intervention. Consider trailing stop after TP1.',
      notesAr: 'خطر تدخل بنك إنجلترا. فكر في وقف متحرك بعد الهدف الأول.',
    },
    {
      title: 'USD/JPY Range Trade',
      titleAr: 'تداول النطاق للدولار مقابل الين',
      currencyPair: 'USD/JPY',
      direction: 'SELL',
      entryPrice: 149.80,
      stopLoss: 150.50,
      takeProfit1: 149.00,
      takeProfit2: 148.30,
      risk: 'LOW',
      confidence: 88,
      summary: 'Strong resistance at 150.50 holds. BOJ intervention fears cap upside.',
      summaryAr: 'مقاومة قوية عند 150.50 تصمد. مخاوف تدخل بنك اليابان تحد من الصعود.',
      trend: 'NEUTRAL',
      technicalAnalysis: 'Price rejected at 150.50 resistance for the third time. RSI rolling over from overbought. Stochastics bearish crossover. Price respecting the established range between 148.00-150.50.',
      technicalAnalysisAr: 'رفض السعر عند مقاومة 150.50 للمرة الثالثة. مؤشر القوة النسبية ينعطف من مناطق التشبع الشرائي. تقاطع عشوائي هابط. السعر يحترم النطاق المحدد بين 148.00-150.50.',
      fundamentalAnalysis: 'BOJ maintains ultra-loose policy but intervention warnings persist. US Treasury yields stabilizing. Carry trade dynamics support JPY shorts.',
      fundamentalAnalysisAr: 'بنك اليابان يحافظ على سياسة التيسير الفائقة لكن تحذيرات التدخل مستمرة. عوائد الخزانة الأمريكية تستقر. ديناميكيات تجارة المناقلة تدعم بيع الين.',
      isPremium: false,
      isPublished: true,
      isApproved: true,
      rsi: 55,
      macdValue: -0.15,
      macdSignal: -0.08,
      macdHistogram: -0.07,
      emaFast: 149.50,
      emaSlow: 149.20,
      smaPeriod: 50,
      smaValue: 149.35,
      atr: 0.65,
      bbUpper: 150.40,
      bbMiddle: 149.50,
      bbLower: 148.60,
      support1: 149.00,
      support2: 148.60,
      support3: 148.00,
      resistance1: 150.00,
      resistance2: 150.50,
      resistance3: 151.20,
      tradesAnalyzed: 1563,
      aiModel: 'gemini-1.5-pro',
      aiProvider: 'GEMINI',
      notes: 'Range trade only; break of 150.50 invalidates the setup.',
      notesAr: 'تداول النطاق فقط; كسر 150.50 يلغي الإعداد.',
    },
    {
      title: 'AUD/USD Break and Retest',
      titleAr: 'اختراق وإعادة اختبار للدولار الأسترالي',
      currencyPair: 'AUD/USD',
      direction: 'BUY',
      entryPrice: 0.6580,
      stopLoss: 0.6530,
      takeProfit1: 0.6630,
      takeProfit2: 0.6680,
      risk: 'MEDIUM',
      confidence: 79,
      summary: 'Breakout from consolidation with successful retest. Commodity prices supporting AUD.',
      summaryAr: 'اختراق من التماسك مع إعادة اختبار ناجحة. أسعار السلع تدعم الدولار الأسترالي.',
      trend: 'BULLISH',
      technicalAnalysis: 'Price broke above the symmetrical triangle and retested the breakout level. Strong bullish candle on retest. RSI holding above 50. MACD bullish. Volume confirming breakout.',
      technicalAnalysisAr: 'اخترق السعر فوق المثلث المتماثل وأعاد اختبار مستوى الاختراق. شمعة صاعدة قوية عند إعادة الاختبار. مؤشر القوة النسبية يحافظ على مستواه فوق 50. مؤشر MACD صاعد. الحجم يؤكد الاختراق.',
      fundamentalAnalysis: 'RBA hawkish hold supports AUD. Iron ore prices rallying. China stimulus measures boosting risk sentiment.',
      fundamentalAnalysisAr: 'تثبيت البنك الاحتياطي الأسترالي المتشدد يدعم الدولار الأسترالي. أسعار خام الحديد ترتفع. إجراءات التحفيز الصينية تعزز معنويات المخاطرة.',
      isPremium: false,
      isPublished: true,
      isApproved: true,
      rsi: 58,
      macdValue: 0.0006,
      macdSignal: 0.0003,
      macdHistogram: 0.0003,
      emaFast: 0.6565,
      emaSlow: 0.6540,
      smaPeriod: 50,
      smaValue: 0.6550,
      atr: 0.0035,
      bbUpper: 0.6620,
      bbMiddle: 0.6560,
      bbLower: 0.6500,
      support1: 0.6540,
      support2: 0.6500,
      support3: 0.6460,
      resistance1: 0.6600,
      resistance2: 0.6650,
      resistance3: 0.6700,
      tradesAnalyzed: 734,
      aiModel: 'gpt-4-turbo',
      aiProvider: 'OPENAI',
      notes: 'China GDP data next week could impact. Keep position size moderate.',
      notesAr: 'بيانات الناتج المحلي الإجمالي للصين الأسبوع المقبل قد تؤثر. حافظ على حجم مركز معتدل.',
    },
    {
      title: 'USD/CAD Bearish Momentum',
      titleAr: 'زخم هابط للدولار مقابل الدولار الكندي',
      currencyPair: 'USD/CAD',
      direction: 'SELL',
      entryPrice: 1.3620,
      stopLoss: 1.3680,
      takeProfit1: 1.3560,
      takeProfit2: 1.3500,
      risk: 'MEDIUM',
      confidence: 81,
      summary: 'Sustained breakdown below 1.3650 support. Oil prices rallying support CAD.',
      summaryAr: 'انهيار مستدام تحت دعم 1.3650. أسعار النفط ترتفع تدعم الدولار الكندي.',
      trend: 'BEARISH',
      technicalAnalysis: 'Price broke below the 50-day SMA and key support at 1.3650. Lower highs forming. RSI below 50 and declining. MACD bearish crossover confirmed. Increased selling volume.',
      technicalAnalysisAr: 'اخترق السعر أسفل المتوسط المتحرك لـ50 يومًا والدعم الرئيسي عند 1.3650. قمم أدنى تتشكل. مؤشر القوة النسبية تحت 50 وفي انخفاض. تأكيد تقاطع هابط لمؤشر MACD. زيادة حجم البيع.',
      fundamentalAnalysis: 'BoC hold with hawkish tone. Oil prices at multi-month highs benefiting Canadian economy. US dollar weakening broadly.',
      fundamentalAnalysisAr: 'تثبيت بنك كندا بنبرة متشددة. أسعار النفط عند أعلى مستوياتها في عدة أشهر تفيد الاقتصاد الكندي. تراجع الدولار الأمريكي على نطاق واسع.',
      isPremium: true,
      isPublished: true,
      isApproved: true,
      rsi: 42,
      macdValue: -0.0015,
      macdSignal: -0.0008,
      macdHistogram: -0.0007,
      emaFast: 1.3635,
      emaSlow: 1.3655,
      smaPeriod: 50,
      smaValue: 1.3650,
      atr: 0.0040,
      bbUpper: 1.3700,
      bbMiddle: 1.3630,
      bbLower: 1.3560,
      support1: 1.3560,
      support2: 1.3520,
      support3: 1.3450,
      resistance1: 1.3650,
      resistance2: 1.3680,
      resistance3: 1.3720,
      tradesAnalyzed: 1105,
      aiModel: 'deepseek-chat',
      aiProvider: 'DEEPSEEK',
      notes: 'Oil inventory data Wednesday. USDCAD correlation with WTI strong.',
      notesAr: 'بيانات مخزون النفط يوم الأربعاء. ارتباط الدولار الكندي بخام غرب تكساس قوي.',
    },
    {
      title: 'NZD/USD Support Bounce',
      titleAr: 'ارتداد من الدعم للدولار النيوزيلندي',
      currencyPair: 'NZD/USD',
      direction: 'BUY',
      entryPrice: 0.6080,
      stopLoss: 0.6040,
      takeProfit1: 0.6120,
      takeProfit2: 0.6160,
      risk: 'LOW',
      confidence: 85,
      summary: 'Double bottom formation at key support. RSI oversold bounce anticipated.',
      summaryAr: 'تشكيل قاع مزدوج عند دعم رئيسي. ارتداد متوقع من مناطق تشبع بيع لمؤشر القوة النسبية.',
      trend: 'BULLISH',
      technicalAnalysis: 'Double bottom pattern at 0.6050 level. Bullish divergence on RSI. Stochastics oversold with crossover. Price holding above 200-day MA. Volume declining on sell-offs suggesting exhaustion.',
      technicalAnalysisAr: 'نمط القاع المزدوج عند مستوى 0.6050. تباعد صاعد على مؤشر القوة النسبية. مؤشر العشوائية في تشبع بيع مع تقاطع. السعر يحافظ على مستواه فوق المتوسط المتحرك لـ200 يوم. الحجم يتراجع مع عمليات البيع مما يشير إلى الإرهاق.',
      fundamentalAnalysis: 'RBNZ rate decision next week. Dairy prices stabilizing. Risk sentiment improving broadly.',
      fundamentalAnalysisAr: 'قرار سعر الفائدة للبنك الاحتياطي النيوزيلندي الأسبوع المقبل. أسعار الألبان تستقر. معنويات المخاطرة تتحسن على نطاق واسع.',
      isPremium: false,
      isPublished: true,
      isApproved: true,
      rsi: 35,
      macdValue: -0.0004,
      macdSignal: -0.0007,
      macdHistogram: 0.0003,
      emaFast: 0.6075,
      emaSlow: 0.6090,
      smaPeriod: 50,
      smaValue: 0.6085,
      atr: 0.0030,
      bbUpper: 0.6140,
      bbMiddle: 0.6080,
      bbLower: 0.6020,
      support1: 0.6050,
      support2: 0.6020,
      support3: 0.5980,
      resistance1: 0.6100,
      resistance2: 0.6140,
      resistance3: 0.6180,
      tradesAnalyzed: 678,
      aiModel: 'claude-3-sonnet',
      aiProvider: 'CLAUDE',
      notes: 'RBNZ decision is key risk event. Consider hedging.',
      notesAr: 'قرار البنك الاحتياطي النيوزيلندي هو حدث الخطر الرئيسي. فكر في التحوط.',
    },
    {
      title: 'EUR/GBP Momentum Breakout',
      titleAr: 'اختراق الزخم لليورو مقابل الجنيه',
      currencyPair: 'EUR/GBP',
      direction: 'BUY',
      entryPrice: 0.8580,
      stopLoss: 0.8540,
      takeProfit1: 0.8620,
      takeProfit2: 0.8660,
      risk: 'MEDIUM',
      confidence: 77,
      summary: 'Bullish flag pattern with strong upside momentum. ECB-BoE policy divergence widening.',
      summaryAr: 'نمط العلم الصاعد مع زخم صاعد قوي. تباعد سياسات البنك المركزي الأوروبي وبنك إنجلترا يتسع.',
      trend: 'BULLISH',
      technicalAnalysis: 'Bull flag breakout with strong volume. RSI at 60 and rising. MACD bullish with increasing histogram. Price above all major moving averages. Bollinger Bands expanding.',
      technicalAnalysisAr: 'اختراق العلم الصاعد بحجم قوي. مؤشر القوة النسبية عند 60 وفي ارتفاع. مؤشر MACD صاعد مع رسم بياني متزايد. السعر فوق جميع المتوسطات المتحركة الرئيسية. نطاقات بولينجر تتسع.',
      fundamentalAnalysis: 'ECB hawkish vs BoE dovish expectations. Eurozone inflation sticky. UK economy showing weakness.',
      fundamentalAnalysisAr: 'توقعات البنك المركزي الأوروبي المتشددة مقابل توقعات بنك إنجلترا المتساهلة. تضخم منطقة اليورو ثابت. الاقتصاد البريطاني يظهر ضعفًا.',
      isPremium: true,
      isPublished: true,
      isApproved: true,
      rsi: 60,
      macdValue: 0.0009,
      macdSignal: 0.0005,
      macdHistogram: 0.0004,
      emaFast: 0.8565,
      emaSlow: 0.8545,
      smaPeriod: 50,
      smaValue: 0.8555,
      atr: 0.0028,
      bbUpper: 0.8610,
      bbMiddle: 0.8560,
      bbLower: 0.8510,
      support1: 0.8550,
      support2: 0.8520,
      support3: 0.8480,
      resistance1: 0.8600,
      resistance2: 0.8640,
      resistance3: 0.8680,
      tradesAnalyzed: 945,
      aiModel: 'gpt-4o',
      aiProvider: 'OPENAI',
      notes: 'ECB minutes release tomorrow. Monitor UK CPI data.',
      notesAr: 'محضر اجتماع البنك المركزي الأوروبي يصدر غدًا. راقب بيانات مؤشر أسعار المستهلك في المملكة المتحدة.',
    },
    {
      title: 'USD/CHF Trend Continuation',
      titleAr: 'استمرار الاتجاه للدولار مقابل الفرنك',
      currencyPair: 'USD/CHF',
      direction: 'SELL',
      entryPrice: 0.8820,
      stopLoss: 0.8860,
      takeProfit1: 0.8780,
      takeProfit2: 0.8740,
      risk: 'LOW',
      confidence: 83,
      summary: 'Strong downtrend channel intact. SNB intervention risk limits downside but trend is clear.',
      summaryAr: 'قناة الاتجاه الهابط قوية سليمة. خطر تدخل البنك السويسري يحد من الهبوط لكن الاتجاه واضح.',
      trend: 'BEARISH',
      technicalAnalysis: 'Price respecting the descending channel. Consecutive lower highs and lower lows. RSI below 50 and trending down. MACD consistently negative. Strong support at 0.8720.',
      technicalAnalysisAr: 'السعر يحترم القناة الهابطة. قمم أدنى وقيعان أدنى متتالية. مؤشر القوة النسبية تحت 50 وفي اتجاه هابط. مؤشر MACD سلبي باستمرار. دعم قوي عند 0.8720.',
      fundamentalAnalysis: 'Swiss franc strengthening on safe-haven flows. SNB may intervene if USD/CHF drops too fast. US dollar weakness persists.',
      fundamentalAnalysisAr: 'الفرنك السويسري يقوي بفضل تدفقات الملاذ الآمن. قد يتدخل البنك السويسري إذا انخفض زوج الدولار/فرنك بسرعة كبيرة. ضعف الدولار الأمريكي مستمر.',
      isPremium: false,
      isPublished: true,
      isApproved: true,
      rsi: 38,
      macdValue: -0.0010,
      macdSignal: -0.0006,
      macdHistogram: -0.0004,
      emaFast: 0.8830,
      emaSlow: 0.8845,
      smaPeriod: 50,
      smaValue: 0.8835,
      atr: 0.0032,
      bbUpper: 0.8870,
      bbMiddle: 0.8820,
      bbLower: 0.8770,
      support1: 0.8780,
      support2: 0.8750,
      support3: 0.8720,
      resistance1: 0.8840,
      resistance2: 0.8870,
      resistance3: 0.8900,
      tradesAnalyzed: 812,
      aiModel: 'gemini-1.5-flash',
      aiProvider: 'GEMINI',
      notes: 'SNB sight deposits data weekly. Watch for sudden CHF strength.',
      notesAr: 'بيانات الودائع تحت الطلب للبنك السويسري أسبوعيًا. راقب قوة مفاجئة للفرنك.',
    },
    {
      title: 'GBP/JPY Breakout Play',
      titleAr: 'صفقة اختراق للجنيه مقابل الين',
      currencyPair: 'GBP/JPY',
      direction: 'BUY',
      entryPrice: 189.50,
      stopLoss: 188.20,
      takeProfit1: 190.80,
      takeProfit2: 192.00,
      risk: 'HIGH',
      confidence: 73,
      summary: 'Volatility breakout from consolidation. Wide spreads expected. High risk-reward setup.',
      summaryAr: 'اختراق تقلب من التماسك. فروق سعرية واسعة متوقعة. إعداد عالي المخاطرة-المكافأة.',
      trend: 'BULLISH',
      technicalAnalysis: 'Price consolidating in a tight range for 2 weeks. Bollinger Bands squeezing suggesting breakout imminent. RSI neutral but curling up. Volume building. Potential for significant move.',
      technicalAnalysisAr: 'السعر يتماسك في نطاق ضيق لمدة أسبوعين. نطاقات بولينجر تضغط مما يشير إلى اختراق وشيك. مؤشر القوة النسبية محايد لكنه يتجه لأعلى. الحجم يتراكم. احتمالية حركة كبيرة.',
      fundamentalAnalysis: 'GBP gaining on rate expectations. JPY under pressure from BOJ policy. Cross pair highly sensitive to risk sentiment.',
      fundamentalAnalysisAr: 'الجنيه يرتفع بفضل توقعات أسعار الفائدة. الين تحت ضغط من سياسة بنك اليابان. الزوج المتقاطع حساس جدًا لمعنويات المخاطرة.',
      isPremium: true,
      isPublished: true,
      isApproved: false,
      rsi: 52,
      macdValue: 0.05,
      macdSignal: 0.02,
      macdHistogram: 0.03,
      emaFast: 189.20,
      emaSlow: 188.80,
      smaPeriod: 50,
      smaValue: 189.00,
      atr: 1.20,
      bbUpper: 191.00,
      bbMiddle: 189.30,
      bbLower: 187.60,
      support1: 188.50,
      support2: 187.80,
      support3: 186.50,
      resistance1: 190.00,
      resistance2: 190.80,
      resistance3: 192.00,
      tradesAnalyzed: 567,
      aiModel: 'deepseek-chat',
      aiProvider: 'DEEPSEEK',
      notes: 'Pending approval. Very high volatility pair. Use smaller position size.',
      notesAr: 'قيد الانتظار. زوج عالي التقلب جدًا. استخدم حجم مركز أصغر.',
    },
    {
      title: 'EUR/JPY Pullback Entry',
      titleAr: 'دخول ارتدادي لليورو مقابل الين',
      currencyPair: 'EUR/JPY',
      direction: 'BUY',
      entryPrice: 163.20,
      stopLoss: 162.00,
      takeProfit1: 164.40,
      takeProfit2: 165.50,
      risk: 'MEDIUM',
      confidence: 80,
      summary: 'Pullback to Fibonacci 61.8% retracement. Trend still intact on higher timeframes.',
      summaryAr: 'ارتداد إلى مستوى تصحيح فيبوناتشي 61.8%. الاتجاه لا يزال سليمًا على الأطر الزمنية الأعلى.',
      trend: 'BULLISH',
      technicalAnalysis: 'Price retraced to Fibonacci 61.8% level at 163.20. Holding above 200-day MA. RSI approaching oversold in uptrend. MACD bearish but histogram shrinking. Bullish harami forming on daily.',
      technicalAnalysisAr: 'ارتد السعر إلى مستوى فيبوناتشي 61.8% عند 163.20. يحافظ على مستواه فوق المتوسط المتحرك لـ200 يوم. مؤشر القوة النسبية يقترب من التشبع البيعي في اتجاه صاعد. مؤشر MACD هابط لكن الرسم البياني يتقلص. نماذج هارامي الصاعدة تتشكل على اليومي.',
      fundamentalAnalysis: 'EUR supported by rate differentials. JPY remains weak. Cross pair trend strongly bullish on weekly chart.',
      fundamentalAnalysisAr: 'اليورو مدعوم بفروق أسعار الفائدة. الين لا يزال ضعيفًا. اتجاه الزوج المتقاطع صاعد بقوة على الرسم البياني الأسبوعي.',
      isPremium: false,
      isPublished: true,
      isApproved: true,
      rsi: 44,
      macdValue: -0.35,
      macdSignal: -0.20,
      macdHistogram: -0.15,
      emaFast: 163.50,
      emaSlow: 164.00,
      smaPeriod: 50,
      smaValue: 163.80,
      atr: 0.85,
      bbUpper: 165.50,
      bbMiddle: 163.80,
      bbLower: 162.10,
      support1: 162.80,
      support2: 162.00,
      support3: 161.00,
      resistance1: 164.00,
      resistance2: 164.80,
      resistance3: 165.50,
      tradesAnalyzed: 1023,
      aiModel: 'claude-3-opus',
      aiProvider: 'CLAUDE',
      notes: 'Entry at 61.8% fib. Strict stop management essential.',
      notesAr: 'الدخول عند فيبوناتشي 61.8%. إدارة صارمة للوقف ضرورية.',
    },
    {
      title: 'Gold (XAU/USD) Hedge Play',
      titleAr: 'صفقة تحوط في الذهب',
      currencyPair: 'XAU/USD',
      direction: 'BUY',
      entryPrice: 2335.00,
      stopLoss: 2305.00,
      takeProfit1: 2365.00,
      takeProfit2: 2395.00,
      risk: 'MEDIUM',
      confidence: 86,
      summary: 'Geopolitical tensions and rate cut expectations drive safe-haven demand.',
      summaryAr: 'التوترات الجيوسياسية وتوقعات خفض أسعار الفائدة تدفع الطلب على الملاذ الآمن.',
      trend: 'BULLISH',
      technicalAnalysis: 'Price above all major moving averages. Golden cross on daily chart. RSI at 65 with room to run. MACD bullish. Central bank buying continues. Strong support at 2320.',
      technicalAnalysisAr: 'السعر فوق جميع المتوسطات المتحركة الرئيسية. تقاطع ذهبي على الرسم البياني اليومي. مؤشر القوة النسبية عند 65 مع مساحة للارتفاع. مؤشر MACD صاعد. شراء البنوك المركزية مستمر. دعم قوي عند 2320.',
      fundamentalAnalysis: 'Central banks increasing gold reserves. Rate cut cycle approaching. Geopolitical uncertainty elevated. USD weakening supports gold.',
      fundamentalAnalysisAr: 'البنوك المركزية تزيد احتياطيات الذهب. دورة خفض أسعار الفائدة تقترب. عدم اليقين الجيوسياسي مرتفع. ضعف الدولار يدعم الذهب.',
      isPremium: true,
      isPublished: true,
      isApproved: true,
      rsi: 65,
      macdValue: 8.50,
      macdSignal: 5.20,
      macdHistogram: 3.30,
      emaFast: 2328.00,
      emaSlow: 2310.00,
      smaPeriod: 50,
      smaValue: 2320.00,
      atr: 18.50,
      bbUpper: 2360.00,
      bbMiddle: 2330.00,
      bbLower: 2300.00,
      support1: 2320.00,
      support2: 2300.00,
      support3: 2280.00,
      resistance1: 2350.00,
      resistance2: 2370.00,
      resistance3: 2400.00,
      tradesAnalyzed: 2134,
      aiModel: 'gpt-4-turbo',
      aiProvider: 'OPENAI',
      notes: 'FOMC minutes key event. Gold has strong inverse correlation with USD.',
      notesAr: 'محضر اجتماع اللجنة الفيدرالية للسوق المفتوحة حدث رئيسي. الذهب له علاقة عكسية قوية مع الدولار.',
    },
    {
      title: 'BTC/USD Momentum Scalp',
      titleAr: 'مضاربة لحظية على زخم البيتكوين',
      currencyPair: 'BTC/USD',
      direction: 'BUY',
      entryPrice: 67500,
      stopLoss: 66200,
      takeProfit1: 68800,
      takeProfit2: 70000,
      risk: 'HIGH',
      confidence: 71,
      summary: 'Short-term momentum trade on BTC. High volatility expected. Tight risk management required.',
      summaryAr: 'صفقة زخم قصيرة المدى على البيتكوين. تقلب عالي متوقع. إدارة مخاطر صارمة مطلوبة.',
      trend: 'BULLISH',
      technicalAnalysis: 'BTC breaking above short-term resistance at 67000. Volume increasing on spot markets. RSI at 58, not yet overbought. MACD bullish crossover on 1H chart. Support at 66000.',
      technicalAnalysisAr: 'البيتكوين يخترق فوق المقاومة قصيرة المدى عند 67000. الحجم يزيد في الأسواق الفورية. مؤشر القوة النسبية عند 58، لم يصل بعد إلى التشبع الشرائي. تقاطع صاعد لمؤشر MACD على الرسم البياني للساعة. دعم عند 66000.',
      fundamentalAnalysis: 'ETF inflows positive. Institutional accumulation continuing. Regulatory clarity improving. On-chain metrics bullish.',
      fundamentalAnalysisAr: 'تدفقات صناديق المؤشرات المتداولة إيجابية. التراكم المؤسسي مستمر. الوضوح التنظيمي يتحسن. المقاييس على السلسلة صاعدة.',
      isPremium: true,
      isPublished: true,
      isApproved: true,
      rsi: 58,
      macdValue: 350,
      macdSignal: 180,
      macdHistogram: 170,
      emaFast: 67000,
      emaSlow: 66500,
      smaPeriod: 50,
      smaValue: 66800,
      atr: 1200,
      bbUpper: 69000,
      bbMiddle: 67200,
      bbLower: 65400,
      support1: 66000,
      support2: 65000,
      support3: 64000,
      resistance1: 68000,
      resistance2: 69000,
      resistance3: 70000,
      tradesAnalyzed: 3456,
      aiModel: 'gemini-1.5-pro',
      aiProvider: 'GEMINI',
      notes: 'Very high volatility. Short-term scalp trade only. Use tight stop.',
      notesAr: 'تقلب عالي جدًا. صفقة مضاربة قصيرة المدى فقط. استخدم وقف ضيق.',
    },
  ]

  for (const s of strategiesData) {
    await prisma.strategy.create({
      data: {
        title: s.title,
        titleAr: s.titleAr,
        currencyPair: s.currencyPair,
        direction: s.direction,
        entryPrice: s.entryPrice,
        stopLoss: s.stopLoss,
        takeProfit1: s.takeProfit1,
        takeProfit2: s.takeProfit2,
        risk: s.risk,
        confidence: s.confidence,
        summary: s.summary,
        summaryAr: s.summaryAr,
        trend: s.trend,
        technicalAnalysis: s.technicalAnalysis,
        technicalAnalysisAr: s.technicalAnalysisAr,
        fundamentalAnalysis: s.fundamentalAnalysis,
        fundamentalAnalysisAr: s.fundamentalAnalysisAr,
        isPremium: s.isPremium,
        isPublished: s.isPublished,
        isApproved: s.isApproved,
        rsi: s.rsi,
        macdValue: s.macdValue,
        macdSignal: s.macdSignal,
        macdHistogram: s.macdHistogram,
        emaFast: s.emaFast,
        emaSlow: s.emaSlow,
        smaPeriod: s.smaPeriod,
        smaValue: s.smaValue,
        atr: s.atr,
        bbUpper: s.bbUpper,
        bbMiddle: s.bbMiddle,
        bbLower: s.bbLower,
        support1: s.support1,
        support2: s.support2,
        support3: s.support3,
        resistance1: s.resistance1,
        resistance2: s.resistance2,
        resistance3: s.resistance3,
        tradesAnalyzed: s.tradesAnalyzed,
        aiModel: s.aiModel,
        aiProvider: s.aiProvider,
        notes: s.notes,
        notesAr: s.notesAr,
        publishedAt: new Date(),
      },
    })
  }
  console.log(`  ✓ ${strategiesData.length} strategies created`)

  // ── Testimonials ────────────────────────────────────────────────────────
  const testimonials = [
    {
      name: 'Abdulrahman Al-Saud',
      nameAr: 'عبدالرحمن آل سعود',
      role: 'Professional Trader',
      roleAr: 'متداول محترف',
      content: 'YuanBridge has transformed my trading. The AI strategies are incredibly accurate and the real-time analysis saves me hours of research every day.',
      contentAr: 'غيَّر يوان بريدج تداولي بشكل كامل. استراتيجيات الذكاء الاصطناعي دقيقة بشكل لا يصدق والتحليل الفوري يوفر لي ساعات من البحث كل يوم.',
      rating: 5,
      avatar: null,
    },
    {
      name: 'Layla Mansouri',
      nameAr: 'ليلى المنصوري',
      role: 'Forex Trader',
      roleAr: 'متداولة فوركس',
      content: 'The bilingual support is amazing. I can switch between Arabic and English seamlessly. The premium subscription is worth every dollar.',
      contentAr: 'الدعم ثنائي اللغة رائع. يمكنني التبديل بين العربية والإنجليزية بسلاسة. الاشتراك المميز يستحق كل دولار.',
      rating: 5,
      avatar: null,
    },
    {
      name: 'James Mitchell',
      nameAr: 'جيمس ميتشل',
      role: 'Investment Analyst',
      roleAr: 'محلل استثمار',
      content: 'I\'ve been using YuanBridge for 3 months. The market data coverage and AI-generated strategies have consistently outperformed my manual analysis.',
      contentAr: 'أستخدم يوان بريدج منذ 3 أشهر. تغطية بيانات السوق والاستراتيجيات المولدة بالذكاء الاصطناعي تفوق باستمرار تحليلي اليدوي.',
      rating: 4,
      avatar: null,
    },
    {
      name: 'Nora Al-Qahtani',
      nameAr: 'نورة القحطاني',
      role: 'Day Trader',
      roleAr: 'متداولة يومية',
      content: 'The real-time notifications keep me updated on market movements 24/7. The risk management tools have helped me minimize losses significantly.',
      contentAr: 'الإشعارات الفورية تبقيني على اطلاع دائم بحركات السوق على مدار الساعة. أدوات إدارة المخاطر ساعدتني في تقليل الخسائر بشكل كبير.',
      rating: 5,
      avatar: null,
    },
    {
      name: 'David Chen',
      nameAr: 'ديفيد تشين',
      role: 'Swing Trader',
      roleAr: 'متداول تأرجحي',
      content: 'What sets YuanBridge apart is the combination of multiple AI providers. Getting analysis from GPT, Claude, and Gemini gives me a comprehensive market view.',
      contentAr: 'ما يميز يوان بريدج هو الجمع بين مزودي ذكاء اصطناعي متعددين. الحصول على تحليل من GPT وكلود وجيميني يعطيني نظرة شاملة للسوق.',
      rating: 5,
      avatar: null,
    },
  ]

  for (const t of testimonials) {
    await prisma.testimonial.create({ data: t })
  }
  console.log(`  ✓ ${testimonials.length} testimonials created`)

  // ── FAQ Items ───────────────────────────────────────────────────────────
  const faqs = [
    {
      question: 'What is YuanBridge AI?',
      questionAr: 'ما هو يوان بريدج للذكاء الاصطناعي؟',
      answer: 'YuanBridge is an AI-powered Forex trading platform that generates real-time strategies using multiple AI providers including GPT-4, Claude, Gemini, and DeepSeek. We analyze market data 24/7 to provide actionable trading insights.',
      answerAr: 'يوان بريدج هي منصة تداول فوركس مدعومة بالذكاء الاصطناعي تولد استراتيجيات فورية باستخدام مزودي ذكاء اصطناعي متعددين بما في ذلك GPT-4 وكلود وجيميني وديب سيك. نحلل بيانات السوق على مدار الساعة لتوفير رؤى تداول قابلة للتنفيذ.',
      order: 1,
    },
    {
      question: 'How much does premium cost?',
      questionAr: 'كم تكلفة الاشتراك المميز؟',
      answer: 'Premium subscription is $15 per month. This includes unlimited AI strategy generation, real-time market data, priority support, and access to advanced technical indicators.',
      answerAr: 'الاشتراك المميز هو 15 دولارًا شهريًا. يشمل ذلك توليد استراتيجيات غير محدودة بالذكاء الاصطناعي وبيانات سوق فورية ودعم ذو أولوية والوصول إلى مؤشرات فنية متقدمة.',
      order: 2,
    },
    {
      question: 'Which payment methods do you accept?',
      questionAr: 'ما هي طرق الدفع التي تقبلونها؟',
      answer: 'We accept payments via Stripe (credit/debit cards) and PayPal. All transactions are secured and encrypted. Your payment information is never stored on our servers.',
      answerAr: 'نقبل الدفع عبر Stripe (بطاقات الائتمان/الخصم) وباي بال. جميع المعاملات آمنة ومشفرة. معلومات الدفع الخاصة بك لا تُخزن أبدًا على خوادمنا.',
      order: 3,
    },
    {
      question: 'Is the platform available in Arabic?',
      questionAr: 'هل المنصة متاحة باللغة العربية؟',
      answer: 'Yes! YuanBridge is fully bilingual with support for both Arabic and English. All strategies, analysis, and interface elements are available in both languages. You can switch anytime.',
      answerAr: 'نعم! يوان بريدج ثنائي اللغة بالكامل مع دعم كل من العربية والإنجليزية. جميع الاستراتيجيات والتحليلات وعناصر الواجهة متاحة باللغتين. يمكنك التبديل في أي وقت.',
      order: 4,
    },
    {
      question: 'How are strategies generated?',
      questionAr: 'كيف يتم توليد الاستراتيجيات؟',
      answer: 'Our AI engine combines technical analysis, fundamental analysis, and market sentiment data. Each strategy is analyzed by multiple AI models and validated against historical data before publication.',
      answerAr: 'يجمع محرك الذكاء الاصطناعي لدينا بين التحليل الفني والتحليل الأساسي وبيانات معنويات السوق. يتم تحليل كل استراتيجية بواسطة نماذج ذكاء اصطناعي متعددة والتحقق من صحتها مقابل البيانات التاريخية قبل النشر.',
      order: 5,
    },
    {
      question: 'Can I cancel my subscription anytime?',
      questionAr: 'هل يمكنني إلغاء اشتراكي في أي وقت؟',
      answer: 'Yes, you can cancel your subscription at any time. Your premium access will continue until the end of your billing period. No cancellation fees.',
      answerAr: 'نعم، يمكنك إلغاء اشتراكك في أي وقت. سيستمر وصولك المميز حتى نهاية فترة الفوترة الخاصة بك. لا توجد رسوم إلغاء.',
      order: 6,
    },
    {
      question: 'What currency pairs do you cover?',
      questionAr: 'ما هي أزواج العملات التي تغطيها؟',
      answer: 'We cover all major pairs (EUR/USD, GBP/USD, USD/JPY, USD/CHF, AUD/USD, USD/CAD, NZD/USD), minor pairs, and exotics. We also cover commodities like XAU/USD (Gold) and cryptocurrencies like BTC/USD.',
      answerAr: 'نغطي جميع الأزواج الرئيسية (EUR/USD, GBP/USD, USD/JPY, USD/CHF, AUD/USD, USD/CAD, NZD/USD) والأزواج الثانوية والغريبة. كما نغطي السلع مثل XAU/USD (الذهب) والعملات الرقمية مثل BTC/USD.',
      order: 7,
    },
    {
      question: 'How do I get started?',
      questionAr: 'كيف أبدأ؟',
      answer: 'Simply create a free account and start exploring the dashboard. Free users get limited access to strategies. Upgrade to premium for full access. No credit card required for the free tier.',
      answerAr: 'ببساطة أنشئ حسابًا مجانيًا وابدأ في استكشاف لوحة التحكم. المستخدمون المجانيون يحصلون على وصول محدود للاستراتيجيات. قم بالترقية إلى المميز للوصول الكامل. لا حاجة لبطاقة ائتمان للطبقة المجانية.',
      order: 8,
    },
    {
      question: 'Is my data secure?',
      questionAr: 'هل بياناتي آمنة؟',
      answer: 'Absolutely. We use enterprise-grade encryption for all data in transit and at rest. We are GDPR compliant. Your trading data and personal information are never shared with third parties.',
      answerAr: 'بالتأكيد. نستخدم تشفيرًا على مستوى المؤسسات لجميع البيانات المنقولة والمخزنة. نحن متوافقون مع اللائحة العامة لحماية البيانات. بيانات التداول والمعلومات الشخصية الخاصة بك لا تتم مشاركتها أبدًا مع أطراف ثالثة.',
      order: 9,
    },
    {
      question: 'Do you offer refunds?',
      questionAr: 'هل تقدمون استرداد الأموال؟',
      answer: 'We offer a 7-day money-back guarantee for new premium subscribers. If you are not satisfied within the first 7 days, contact our support team for a full refund.',
      answerAr: 'نقدم ضمان استرداد الأموال لمدة 7 أيام للمشتركين الجدد في الخطة المميزة. إذا لم تكن راضيًا خلال الأيام السبعة الأولى، اتصل بفريق الدعم لدينا لاسترداد كامل المبلغ.',
      order: 10,
    },
  ]

  for (const f of faqs) {
    await prisma.fAQ.create({ data: f })
  }
  console.log(`  ✓ ${faqs.length} FAQ items created`)

  // ── App Settings ─────────────────────────────────────────────────────────
  const settings: { key: string; value: string }[] = [
    { key: 'site_name', value: 'YuanBridge AI' },
    { key: 'site_description', value: 'AI-Powered Forex Trading Strategies Platform' },
    { key: 'site_description_ar', value: 'منصة استراتيجيات تداول الفوركس المدعومة بالذكاء الاصطناعي' },
    { key: 'premium_price', value: '15' },
    { key: 'premium_currency', value: 'USD' },
    { key: 'premium_interval', value: 'month' },
    { key: 'free_strategies_per_day', value: '3' },
    { key: 'maintenance_mode', value: 'false' },
    { key: 'default_language', value: 'ar' },
    { key: 'default_theme', value: 'dark' },
    { key: 'trial_days', value: '7' },
    { key: 'support_email', value: 'support@yuanbridge.com' },
    { key: 'enable_telegram_notifications', value: 'true' },
    { key: 'enable_email_notifications', value: 'true' },
  ]

  for (const s of settings) {
    await prisma.appSetting.upsert({
      where: { key: s.key },
      update: { value: s.value },
      create: { key: s.key, value: s.value },
    })
  }
  console.log(`  ✓ ${settings.length} app settings created`)

  console.log('\n✓ Seeding complete!')
}

function sixtyDays(days: number): number {
  return days * 24 * 60 * 60 * 1000
}

main()
  .catch((e) => {
    console.error('Seeding failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
